config/routes.rb
Web::Application.routes.draw do
  
  devise_for :users
  
  resources :boards do
   resources :posts
  end
  
  namespace :admin do 
    resources :boards do
     resources :posts
    end
  end

  

   root :to => 'boards#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :posts
  attr_accessible :name
  scope :recent, :order => "updated_at DESC"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :board, :counter_cache => true
  attr_accessible :content, :title, :image
  scope :recent, :order => "updated_at DESC"
  has_attached_file :image, :styles => { :show => "640X480>", :thumb => "100X100#" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :is_admin
  # attr_accessible :title, :body
  
  def is_admin?
    is_admin
  end
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  layout "admin"
  before_filter :require_is_admin
  
  def index
    @boards = Board.recent.paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html
    end
  end
  
  def new
    @board = Board.new
  end
    
  def edit
    @board = Board.find(params[:id])
  end
  
  def create
    @board = Board.new(params[:board])
    
    respond_to do |format|
      if @board.save
        format.html { redirect_to board_path(@board), :notice => "Board was successfully created."}
      end
    end
  end
  
  def update
    @board = Board.find(params[:id])
    @board.update_attributes(params[:board])
    
    respond_to do |format|
      format.html { redirect_to(board_path, :notice => "Board was successfully updated.") }
    end
  end
  
  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_boards_url }
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"
  before_filter :require_is_admin
  before_filter :find_board
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    
    respond_to do |format|
      format.html { redirect_to board_post_path(@board,@post), :notice => "Post was successfully updated." }
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to board_posts_path(@board,@post) }
    end
  end
  
  protected
  
  def find_board
    @board = Board.find(params[:board_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def require_is_admin
    unless current_user && current_user.is_admin?
      flash[:alert] = "You must be admin!"
      redirect_to root_path
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  
  def index
    @boards = Board.recent.paginate(:page => params[:page], :per_page => 5)
  end
  
  def show
    @board = Board.find(params[:id])
    @posts = @board.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :find_board
  before_filter :authenticate_user!, :except => [ :show, :index ]
  
  def index
    redirect_to board_path(@board)
  end
  
  def show
    @post = @board.posts.find(params[:id])
  end
  
  def new
    @post = @board.posts.build
  end
  
  def edit
    @post = current_user.posts.find(params[:id])
  end
  
  def create
    @post = @board.posts.build(params[:post])
    @post.user_id = current_user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to board_post_path(@board, @post), :notice => "Post was successfully updated." }
      end
    end
  end
  
  def update
    @post = current_user.posts.find(params[:id])
    @post.update_attributes(params[:post])
    
    respond_to do |format|
      format.html { redirect_to board_post_path(@board,@post), :notice => "Post was successfully updated." }
    end
  end
  
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to board_posts_path(@board,@post) }
    end
  end
  
  protected
  
  def find_board
    @board = Board.find(params[:board_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/admin/boards/_form.html.erb
<div>
  <%= f.label :Name %><br />
  <%= f.text_field :name %>
</div>

<div>
  <%= f.submit %>
</div>

app/views/admin/boards/edit.html.erb
<h1>Editing board</h1>

<%= form_for @board, :url => admin_board_path do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>

<%= link_to "Show", @board %> |
<%= link_to "Back", admin_boards_path %>

app/views/admin/boards/index.html.erb
<div>
  <h1>Boards</h1>
  <p>Board Name</p>
  <ul>
    <% @boards.each do |board| %>
      <li>
        <%= board.name %> 
        <%= link_to "show", board_path(board)%>
        <%= link_to "Edit", edit_admin_board_path(board) %>
        <%= link_to "Delete", admin_board_path(board), :data => { :confirm => "Are you sure?" }, :method => :delete %>
      </li>
    <% end %>
  </ul>
</div>

<%= will_paginate(@boards) %>
<br />
<%= link_to "New Board", new_admin_board_path %>

app/views/admin/boards/new.html.erb
<h1>New Board</h1>

<%= form_for @board, :url => admin_boards_path(@board) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>
<%= link_to "Back", admin_boards_path %>

app/views/admin/posts/_form.html.erb
<div>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :content %><br />
  <%= f.text_area :content %>
</div>

<div>
  <%= f.label :upload_image %><br />
  <%= f.file_field :image %>
</div>

<div>
  <%= image_tag @post.image.url(:thumb) %>
</div>

<div>
  <%= f.submit %>
</div>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= form_for @post, :url => admin_board_post_path(@board,@post) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>

<%= link_to "Show", board_post_path(@board,@post) %> |
<%= link_to "Back", board_posts_path(@board) %>

app/views/boards/index.html.erb
<div>
  <h1>測試 Boards</h1>
  <p>Board Name</p>
  <ul>
    <% @boards.each do |board| %>
      <li>
        <%= board.name %> 
        <%= link_to "show", board_path(board) %>
        <% if current_user && current_user.is_admin? %>
          <%= link_to "A-Edit", edit_admin_board_path(board) %>
          <%= link_to "A-Destroy", admin_boards_path, :confirm => "Are you sure?", :method => :delete %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<%= will_paginate(@boards) %>
<br />

<% if current_user && current_user.is_admin %>
  <%= link_to "A-New Board", new_admin_board_path %>
<% end %>

app/views/boards/show.html.erb
<div>
  <p>Name:</p>
  <%= @board.name %>
</div>

<h1>Listing posts - Total <%= @board.posts.size %> posts</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Content</th>
    <th>Created At</th>
    <th>Updated</th>
  </tr>
  <% @posts.each do |post| %>
  <tr>
    <td><%=post.id%></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= l(post.created_at, :format => :short) %></td>
    <td><%= l(post.updated_at, :format => :short) %></td>
    <td><%= link_to "Show",board_post_path(@board,post) %></td>
    <% if current_user && post.user == current_user %>
      <td><%= link_to "Edit", edit_board_post_path(@board,post) %></td>
      <td><%= link_to "Delete", board_post_path(@board,post), :confirm => "Are you sure?", :method => :delete %></td>
    <% end %>
    
    <% if current_user && current_user.is_admin %>
      <td><%= link_to "A-Edit",edit_admin_board_post_path(@board,post) %></td>
      <td><%= link_to "A-Destroy", admin_board_post_path(@board,post), :confirm => "Are you sure?", :method => :delete %></td>
    <% end %>
  </tr>
  <% end %>
</table>
<%= will_paginate(@posts) %>
<br />
<%= link_to "New Post", new_board_post_path(@board) %> |
<% if current_user && current_user.is_admin %>
  <%= link_to "A-Edit", edit_admin_board_path(@board) %> |
<% end %>
<%= link_to "Back", boards_path %>

app/views/common/_user_nav.erb
<div class="user_navigation">
  <% if user_signed_in? %>
    Hi!<%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path %>
    <% if current_user.is_admin? %>
      <%= link_to "Admin Panel", admin_boards_path %>
    <% end %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Admin Panel</h1>
  <%= render :partial => "common/user_nav" %>
  <%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "common/user_nav" %>
  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :content %><br />
  <%= f.text_area :content %>
</div>

<div>
  <%= f.label :upload_image %><br />
  <%= f.file_field :image %>
</div>

<div>
  <%= image_tag @post.image.url(:thumb) %>
</div>

<div>
  <%= f.submit %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= form_for @post, :url => board_post_path(@board,@post), :html => { :multipart => true } do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>

<%= link_to "Show", board_post_path(@board,@post) %> |
<%= link_to "Back", board_posts_path(@board) %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_for @post, :url => board_posts_path(@board), :html => { :multipart => true } do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>

<%= link_to "Back", board_posts_path(@board) %>

app/views/posts/show.html.erb
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
  <% if @post.image %>
  <p>
    <%= image_tag @post.image.url(:show) %>
  </p>
  <% end %>
</p>

<% if current_user && current_user.is_admin %>
  <%= link_to "A-Edit", edit_admin_board_post_path(@board, @post) %> |
<% end %>
<%= link_to "Back", board_posts_path(@board) %>